services:<br/>
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - arr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/arr/radarr/config:/config
      - /home/arr/media/Movies/:/movies
      - /home/arr/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: always
networks:
  arr:
    name: arr
    external: true
