packer {
  required_plugins {
    name = {
      version = "1.2.0"
      source  = "github.com/hashicorp/proxmox"
    }
  }
}

variable "proxmox_api_url" {
    type = string
}

variable "proxmox_api_token_id" {
    type = string
}

variable "proxmox_api_token_secret" {
    type = string
    sensitive = true
}

variable "proxmox_node" {
    type = string
}

variable "ssh_password" {
    type = string
    sensitive = true
    description = "Unencrypted root password for the VM"
}

variable "timezone" {
    type = string
    description = "Timezone for the VM"
}

variable "ssh_public_key" {
    type = string
    description = "SSH public key to add to root account"
}

variable "ssh_certificate" {
    type = string
    sensitive = true
    description = "Unencrypted root password for the VM"
}

variable "vm_cores" {
    type = string
    description = "Number of CPU cores for the VM"
}

variable "vm_memory" {
    type = string
    description = "Amount of memory for the VM in MB"
}

variable "vm_disk_size" {
    type = string
    description = "Disk size for the VM"
}

variable "vm_storage_pool" {
    type = string
    description = "Storage pool for VM disk"
}

variable "vm_disk_format" {
    type = string
    description = "Disk format (raw, qcow2, etc.)"
}

variable "iso_storage_pool" {
    type = string
    description = "Storage pool for ISO files"
}

variable "almalinux10_iso" {
    type = string
    description = "Path to the AlmaLinux 10 ISO file"
}



source "proxmox-iso" "autogenerated_1" {
    insecure_skip_tls_verify  = "true"
    proxmox_url = "${var.proxmox_api_url}"
    username = "${var.proxmox_api_token_id}"
    token = "${var.proxmox_api_token_secret}"

    node = "${var.proxmox_node}"

    boot_command = ["e<down><down><leftCtrlOn>e<leftCtrlOff><spacebar>inst.ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/inst.ks<leftCtrlOn>x<leftCtrlOff><wait>"]
    boot_wait    = "5s"

    vm_name = "almalinux10"
    template_description = "10"

    boot_iso {
        iso_file = "${var.almalinux10_iso}"
        iso_storage_pool = "${var.iso_storage_pool}"
        unmount = true
    }

    template_name = "packer-almalinux10"

    qemu_agent = true

    scsi_controller = "virtio-scsi-single"
    bios = "ovmf"
    machine = "q35"
    efi_config {
      efi_storage_pool = "${var.vm_storage_pool}"
      pre_enrolled_keys = true
      efi_format = "raw"
      efi_type = "4m"
    }

    disks {
        disk_size = "${var.vm_disk_size}"
        format = "${var.vm_disk_format}"
        storage_pool = "${var.vm_storage_pool}"
        type = "scsi"

    }

    cores = "${var.vm_cores}"
    memory = "${var.vm_memory}"
    cpu_type = "host"
    network_adapters {
        model = "virtio"
        bridge = "vmbr2"
        firewall = "false"
    }

    cloud_init = true
    cloud_init_storage_pool = "${var.vm_storage_pool}"

    http_content = {
        "/inst.ks" = templatefile("http/inst.ks.pkrtpl.hcl", {
            root_password = var.ssh_password
            ssh_public_key = var.ssh_public_key
            timezone = var.timezone
        })
    }

    ssh_username = "root"
    ssh_private_key_file = "${var.ssh_certificate}"
    ssh_timeout = "20m"

}

build {
  sources = ["source.proxmox-iso.autogenerated_1"]

  name = "proxmox-al10"

  provisioner "shell" {
    inline = [
      "yum install -y cloud-init",
      "systemctl enable qemu-guest-agent",
      "shred -u /etc/ssh/*_key /etc/ssh/*_key.pub",
      "rm -f /var/run/utmp",
      ">/var/log/lastlog",
      ">/var/log/wtmp",
      ">/var/log/btmp",
      "rm -rf /tmp/* /var/tmp/*",
      "unset HISTFILE; rm -rf /home/*/.*history /root/.*history",
      "rm -f /root/*ks",
    ]
  }
}
